# Generated by Django 5.1.15 on 2026-08-17 16:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConviteUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail do Convidado')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('role', models.CharField(choices=[('MASTER_ADMIN', 'Master Admin'), ('DIRETOR', 'Diretor(a)'), ('PROFESSOR', 'Professor(a)')], default='PROFESSOR', max_length=20, verbose_name='Perfil Concedido')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token de Acesso')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('expira_em', models.DateTimeField(verbose_name='Expira em')),
                ('utilizado', models.BooleanField(default=False, verbose_name='Já Utilizado')),
            ],
            options={
                'verbose_name': 'Convite de Usuário',
                'verbose_name_plural': 'Convites de Usuários',
                'ordering': ['-criado_em'],
            },
        ),
    ]
