# Generated by Django 5.1.15 on 2026-08-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_conviteusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conviteusuario',
            name='role',
            field=models.CharField(choices=[('MASTER_ADMIN', 'Master Admin'), ('DIRETOR', 'Diretor(a)'), ('COORDENADOR', 'Coordenador(a)'), ('PROFESSOR', 'Professor(a)'), ('AUXILIAR', 'Auxiliar')], default='PROFESSOR', max_length=20, verbose_name='Perfil Concedido'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MASTER_ADMIN', 'Master Admin'), ('DIRETOR', 'Diretor(a)'), ('COORDENADOR', 'Coordenador(a)'), ('PROFESSOR', 'Professor(a)'), ('AUXILIAR', 'Auxiliar')], default='PROFESSOR', max_length=20, verbose_name='Perfil de Acesso'),
        ),
    ]
