# Generated by Django 5.1.15 on 2026-08-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_conviteusuario_role_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conviteusuario',
            name='role',
            field=models.CharField(choices=[('MASTER_ADMIN', 'Master Admin'), ('DIRETOR', 'Diretor(a)'), ('COORDENADOR', 'Coordenador(a)'), ('ENFERMEIRA', 'Enfermeira'), ('PROFESSOR', 'Professor(a)'), ('AUXILIAR', 'Auxiliar')], default='PROFESSOR', max_length=20, verbose_name='Perfil Concedido'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MASTER_ADMIN', 'Master Admin'), ('DIRETOR', 'Diretor(a)'), ('COORDENADOR', 'Coordenador(a)'), ('ENFERMEIRA', 'Enfermeira'), ('PROFESSOR', 'Professor(a)'), ('AUXILIAR', 'Auxiliar')], default='PROFESSOR', max_length=20, verbose_name='Perfil de Acesso'),
        ),
    ]
