# Generated by Django 5.1.15 on 2026-09-08 02:03

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presencas', '0018_ocorrenciacaderno_modificado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPapelaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Item')),
                ('especificacao', models.TextField(blank=True, verbose_name='Especificação / Detalhes / Marca')),
                ('categoria', models.CharField(choices=[('papeis', 'Papéis e Cartolinas'), ('colas', 'Colas e Adesivos'), ('pintura', 'Pintura e Desenho'), ('escritorio', 'Material de Escritório'), ('higiene', 'Higiene e Cuidados'), ('decoracao', 'Decoração e Eventos'), ('diversos', 'Diversos')], default='diversos', max_length=30, verbose_name='Categoria')),
                ('unidade_medida', models.CharField(choices=[('unidade', 'Unidade(s)'), ('resma', 'Resma(s)'), ('cartela', 'Cartela(s)'), ('litro', 'Litro(s) / Frasco(s)'), ('caixa', 'Caixa(s)'), ('pacote', 'Pacote(s)'), ('bloco', 'Bloco(s)'), ('rolo', 'Rolo(s)'), ('metro', 'Metro(s)'), ('kit', 'Kit / Conjunto')], default='unidade', max_length=30, verbose_name='Unidade de Medida')),
                ('quantidade_estoque', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Saldo Atual em Estoque')),
                ('estoque_minimo', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10, verbose_name='Estoque Mínimo')),
                ('solicitar_pais', models.BooleanField(default=True, help_text='Indica se este item aparecerá no relatório oficial enviado aos pais.', verbose_name='Incluir na Lista dos Pais')),
                ('quantidade_sugerida_pais', models.CharField(blank=True, help_text='Exemplo: 01 unidade, 02 caixas, 04 de cada cor, 20 cartelas', max_length=100, verbose_name='Quantidade Sugerida aos Pais')),
                ('observacao_pais_tipo', models.CharField(blank=True, choices=[('', 'Sem nota de rodapé'), ('sugestao_marca', '(*) Sugestão de marca'), ('higiene_enfermagem', '(**) Higienização / Enfermagem / Berçário')], default='', max_length=30, verbose_name='Nota de Rodapé para Pais')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cadastrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_papelaria_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
            ],
            options={
                'verbose_name': 'Item de Papelaria',
                'verbose_name_plural': 'Itens de Papelaria',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (Compra / Doação)'), ('SAIDA', 'Saída (Consumo Pedagógico / Sala)'), ('AJUSTE', 'Ajuste de Inventário')], max_length=20, verbose_name='Tipo de Movimentação')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Anterior')),
                ('saldo_posterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Posterior')),
                ('motivo', models.CharField(blank=True, max_length=255, verbose_name='Motivo / Observação')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doacoes_papelaria', to='presencas.aluno', verbose_name='Aluno Doador (para Entradas)')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='papelaria.itempapelaria', verbose_name='Item')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_estoque', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo Registro')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos_papelaria', to='presencas.turma', verbose_name='Turma / Sala Destino (para Saídas)')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='itempapelaria',
            index=models.Index(fields=['nome'], name='papelaria_i_nome_f661a1_idx'),
        ),
        migrations.AddIndex(
            model_name='itempapelaria',
            index=models.Index(fields=['categoria'], name='papelaria_i_categor_69b684_idx'),
        ),
        migrations.AddIndex(
            model_name='itempapelaria',
            index=models.Index(fields=['ativo'], name='papelaria_i_ativo_865a83_idx'),
        ),
        migrations.AddIndex(
            model_name='itempapelaria',
            index=models.Index(fields=['solicitar_pais'], name='papelaria_i_solicit_2163ff_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['item', 'data'], name='papelaria_m_item_id_6c9b82_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['tipo', 'data'], name='papelaria_m_tipo_459e43_idx'),
        ),
    ]
