# Generated by Django 5.1.15 on 2026-08-17 16:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presencas', '0003_lancamentochamada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiarioDeClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Aula')),
                ('turno', models.CharField(choices=[('all', 'Todos os Turnos'), ('integral', 'Integral'), ('matutino', 'Matutino'), ('vespertino', 'Vespertino')], default='all', max_length=20, verbose_name='Turno do Lançamento')),
                ('observacao', models.TextField(blank=True, help_text='Anotações gerais sobre o dia da turma (ocorrências, avisos, etc.)', null=True, verbose_name='Observações do Dia')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Diário de Classe',
                'verbose_name_plural': 'Diários de Classe',
                'ordering': ['-data', 'turma__nome'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='lancamentochamada',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lancamentochamada',
            name='registrado_por',
        ),
        migrations.RemoveField(
            model_name='lancamentochamada',
            name='turma',
        ),
        migrations.AlterUniqueTogether(
            name='registropresenca',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to='presencas.turma', verbose_name='Turma / Sala'),
        ),
        migrations.AlterField(
            model_name='registropresenca',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presencas', to='presencas.aluno', verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='registropresenca',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação / Justificativa'),
        ),
        migrations.AlterField(
            model_name='registropresenca',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_presenca', to='presencas.turma', verbose_name='Turma'),
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['turma', 'ativo'], name='presencas_a_turma_i_98d30e_idx'),
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['data_entrada'], name='presencas_a_data_en_4c9ca6_idx'),
        ),
        migrations.AddField(
            model_name='diariodeclasse',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarios_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='diariodeclasse',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diarios', to='presencas.turma', verbose_name='Turma / Sala'),
        ),
        migrations.AddField(
            model_name='registropresenca',
            name='diario_classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='presencas.diariodeclasse', verbose_name='Diário de Classe'),
        ),
        migrations.AddIndex(
            model_name='registropresenca',
            index=models.Index(fields=['data', 'turma'], name='presencas_r_data_3fb125_idx'),
        ),
        migrations.AddIndex(
            model_name='registropresenca',
            index=models.Index(fields=['aluno', 'status'], name='presencas_r_aluno_i_189ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='registropresenca',
            index=models.Index(fields=['status', 'data'], name='presencas_r_status_418322_idx'),
        ),
        migrations.AddConstraint(
            model_name='registropresenca',
            constraint=models.UniqueConstraint(fields=('aluno', 'data'), name='unique_registro_aluno_data'),
        ),
        migrations.DeleteModel(
            name='LancamentoChamada',
        ),
        migrations.AddIndex(
            model_name='diariodeclasse',
            index=models.Index(fields=['data', 'turma'], name='presencas_d_data_03e70a_idx'),
        ),
        migrations.AddConstraint(
            model_name='diariodeclasse',
            constraint=models.UniqueConstraint(fields=('turma', 'data', 'turno'), name='unique_diario_turma_data_turno'),
        ),
    ]
