# Generated by Django 5.1.15 on 2026-08-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presencas', '0005_ocorrenciacaderno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='acompanhamento_dias',
            field=models.CharField(blank=True, default='', help_text='Dias da semana separados por vírgula. Ex: seg,qua,sex', max_length=50, verbose_name='Dias de Acompanhamento'),
        ),
    ]
