# Generated by Django 5.1.15 on 2026-08-20 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presencas', '0006_add_acompanhamento_dias_to_aluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='ano_letivo',
        ),
    ]
