# Generated by Django 5.1.15 on 2026-08-20 22:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presencas', '0007_remove_turma_ano_letivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registropresenca',
            name='status_matutino',
            field=models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Falta'), ('JUSTIFICADO', 'Falta Justificada'), ('PENDENTE', 'Pendente'), ('NA', 'Não se Aplica')], default='PENDENTE', max_length=20, verbose_name='Status Matutino'),
        ),
        migrations.AddField(
            model_name='registropresenca',
            name='status_vespertino',
            field=models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Falta'), ('JUSTIFICADO', 'Falta Justificada'), ('PENDENTE', 'Pendente'), ('NA', 'Não se Aplica')], default='PENDENTE', max_length=20, verbose_name='Status Vespertino'),
        ),
        migrations.AlterField(
            model_name='registropresenca',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação / Evidência'),
        ),
        migrations.AlterField(
            model_name='registropresenca',
            name='status',
            field=models.CharField(choices=[('PRESENTE', 'Presente (P)'), ('AUSENTE', 'Falta (F)'), ('JUSTIFICADO', 'Falta Justificada (FJ)'), ('PARCIAL', 'Presença Parcial'), ('RECESSO', 'Recesso Escolar (RE)'), ('FERIADO', 'Feriado (FE)')], default='PRESENTE', max_length=20, verbose_name='Status Geral'),
        ),
        migrations.AddIndex(
            model_name='registropresenca',
            index=models.Index(fields=['data', 'status_matutino'], name='presencas_r_data_07ed96_idx'),
        ),
        migrations.AddIndex(
            model_name='registropresenca',
            index=models.Index(fields=['data', 'status_vespertino'], name='presencas_r_data_554e92_idx'),
        ),
    ]
