# Generated by Django 5.1.15 on 2026-08-20 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presencas', '0008_registropresenca_status_matutino_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrenciacaderno',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do Arquivo Anexo'),
        ),
        migrations.AddField(
            model_name='ocorrenciacaderno',
            name='attachment_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo MIME do Anexo'),
        ),
        migrations.AddField(
            model_name='ocorrenciacaderno',
            name='responsavel',
            field=models.CharField(blank=True, max_length=150, verbose_name='Responsável / Acompanhante'),
        ),
        migrations.AlterField(
            model_name='ocorrenciacaderno',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='attachments/ocorrencias/', verbose_name='Documento / Anexo'),
        ),
        migrations.CreateModel(
            name='RegistroAmamentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data de Utilização')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade de Utilizações no Dia')),
                ('ano', models.IntegerField(db_index=True, verbose_name='Ano')),
                ('mes', models.IntegerField(db_index=True, verbose_name='Mês')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='attachments/amamentacao/', verbose_name='Arquivo Anexo')),
                ('attachment_name', models.CharField(blank=True, max_length=255, verbose_name='Nome do Arquivo Anexo')),
                ('attachment_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo MIME do Anexo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Registro de Amamentação',
                'verbose_name_plural': 'Registros de Amamentação (Sala de Apoio)',
                'ordering': ['-data'],
                'indexes': [models.Index(fields=['ano', 'mes'], name='presencas_r_ano_eb9bf5_idx'), models.Index(fields=['data'], name='presencas_r_data_fe15b4_idx')],
            },
        ),
    ]
