# Generated by Django 5.1.15 on 2026-08-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presencas', '0009_ocorrenciacaderno_attachment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrenciacaderno',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Nome do Arquivo Anexo'),
        ),
        migrations.AlterField(
            model_name='ocorrenciacaderno',
            name='attachment_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tipo MIME do Anexo'),
        ),
        migrations.AlterField(
            model_name='ocorrenciacaderno',
            name='cid',
            field=models.CharField(blank=True, max_length=255, verbose_name='CID (Classificação Internacional de Doenças)'),
        ),
        migrations.AlterField(
            model_name='ocorrenciacaderno',
            name='documento',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='attachments/ocorrencias/', verbose_name='Documento / Anexo'),
        ),
        migrations.AlterField(
            model_name='ocorrenciacaderno',
            name='quantidade',
            field=models.CharField(blank=True, max_length=255, verbose_name='Quantidade / Sessão / Duração'),
        ),
        migrations.AlterField(
            model_name='ocorrenciacaderno',
            name='responsavel',
            field=models.CharField(blank=True, max_length=255, verbose_name='Responsável / Acompanhante'),
        ),
        migrations.AlterField(
            model_name='registroamamentacao',
            name='anexo',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='attachments/amamentacao/', verbose_name='Arquivo Anexo'),
        ),
        migrations.AlterField(
            model_name='registroamamentacao',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Nome do Arquivo Anexo'),
        ),
        migrations.AlterField(
            model_name='registroamamentacao',
            name='attachment_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tipo MIME do Anexo'),
        ),
    ]
