# Generated by Django 5.1.15 on 2026-08-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presencas', '0010_alter_ocorrenciacaderno_attachment_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoFrequenciaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_ano', models.CharField(db_index=True, max_length=7, unique=True, verbose_name='Mês/Ano (YYYY-MM)')),
                ('ano', models.IntegerField(db_index=True, verbose_name='Ano')),
                ('mes', models.IntegerField(db_index=True, verbose_name='Mês')),
                ('matriculados', models.PositiveIntegerField(default=0, verbose_name='Total de Alunos Matriculados')),
                ('presentes_media', models.PositiveIntegerField(default=0, verbose_name='Média de Alunos Presentes / Dia')),
                ('ausentes_media', models.PositiveIntegerField(default=0, verbose_name='Média de Alunos Ausentes / Faltas')),
                ('taxa_frequencia', models.FloatField(default=0.0, verbose_name='Taxa de Frequência (%)')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Histórico Mensal de Frequência',
                'verbose_name_plural': 'Históricos Mensais de Frequência (2019-2026)',
                'ordering': ['-ano', '-mes'],
                'indexes': [models.Index(fields=['ano', 'mes'], name='presencas_h_ano_b4ed83_idx'), models.Index(fields=['mes_ano'], name='presencas_h_mes_ano_f94158_idx')],
            },
        ),
    ]
