# Generated by Django 5.1.15 on 2026-08-21 00:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presencas', '0011_historicofrequenciamensal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='alergias',
            field=models.TextField(blank=True, default='', verbose_name='Alergias'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='comorbidades',
            field=models.TextField(blank=True, default='', verbose_name='Comorbidades / Condições de Saúde'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='restricoes_alimentares',
            field=models.TextField(blank=True, default='', verbose_name='Restrições Alimentares'),
        ),
        migrations.CreateModel(
            name='AtendimentoEnfermaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atendimento', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Atendimento')),
                ('horario', models.TimeField(default=django.utils.timezone.now, verbose_name='Horário do Atendimento')),
                ('motivo', models.CharField(max_length=150, verbose_name='Motivo Principal')),
                ('motivo_detalhado', models.TextField(blank=True, verbose_name='Detalhamento do Motivo / Outros')),
                ('saida_imediata', models.BooleanField(default=False, verbose_name='Saída Imediata (Antecipada)')),
                ('retornara_dia_seguinte', models.BooleanField(default=True, verbose_name='Retornará no Dia Seguinte')),
                ('data_retorno_prevista', models.DateField(blank=True, null=True, verbose_name='Data Prevista de Retorno')),
                ('observacoes_medicas', models.TextField(blank=True, verbose_name='Observações Médicas / Conduta')),
                ('cid', models.CharField(blank=True, max_length=50, verbose_name='CID (Classificação de Doenças)')),
                ('documento_anexo', models.FileField(blank=True, null=True, upload_to='enfermaria/anexos/', verbose_name='Documento Anexo / Atestado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Registro Ativo')),
                ('deletado_em', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos_enfermaria', to='presencas.aluno', verbose_name='Aluno')),
                ('deletado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_deletados', to=settings.AUTH_USER_MODEL, verbose_name='Deletado por')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Atendimento de Enfermaria',
                'verbose_name_plural': 'Atendimentos de Enfermaria',
                'ordering': ['-data_atendimento', '-horario', '-id'],
                'indexes': [models.Index(fields=['data_atendimento', 'ativo'], name='presencas_a_data_at_acff7e_idx'), models.Index(fields=['aluno', 'ativo'], name='presencas_a_aluno_i_0eb6c3_idx')],
            },
        ),
    ]
