# Generated by Django 5.1.15 on 2026-08-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presencas', '0014_popular_historico_frequencia_mensal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atendimentoenfermaria',
            options={'ordering': ['-data_atendimento', '-horario', '-id'], 'verbose_name': 'Atendimento de Enfermagem', 'verbose_name_plural': 'Atendimentos de Enfermagem'},
        ),
        migrations.AddField(
            model_name='registropresenca',
            name='status_chamada',
            field=models.CharField(choices=[('PRESENTE', 'Presente (P)'), ('AUSENTE', 'Falta (F)'), ('JUSTIFICADO', 'Falta Justificada (FJ)'), ('PARCIAL', 'Presença Parcial'), ('RECESSO', 'Recesso Escolar (RE)'), ('FERIADO', 'Feriado (FE)')], default='PRESENTE', max_length=20, verbose_name='Status Base da Chamada'),
        ),
    ]
