# Generated by Django 5.1.15 on 2026-09-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presencas', '0015_alter_atendimentoenfermaria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='acompanhamento_dias',
            field=models.CharField(blank=True, default='', help_text='Dias e horários de acompanhamento. Ex: Ter 15:00, Qui 16:00', max_length=255, verbose_name='Dias e Horários de Acompanhamento'),
        ),
    ]
