# Generated by Django 5.1.15 on 2026-09-08 00:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presencas', '0016_alter_aluno_acompanhamento_dias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='auxiliares',
            field=models.ManyToManyField(blank=True, related_name='turmas_como_auxiliar', to=settings.AUTH_USER_MODEL, verbose_name='Auxiliares da Turma'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='professores',
            field=models.ManyToManyField(blank=True, related_name='turmas_como_professor', to=settings.AUTH_USER_MODEL, verbose_name='Professores Responsáveis'),
        ),
    ]
