# Generated by Django 5.1.15 on 2026-09-08 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presencas', '0017_turma_auxiliares_alter_turma_professores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrenciacaderno',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_caderno_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Última modificação por'),
        ),
        migrations.AddField(
            model_name='registroamamentacao',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amamentacoes_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Última modificação por'),
        ),
        migrations.AlterField(
            model_name='ocorrenciacaderno',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_caderno_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AlterField(
            model_name='registroamamentacao',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amamentacoes_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
    ]
