# Generated by Django 5.1.15 on 2026-09-09 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presencas', '0018_ocorrenciacaderno_modificado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaNaoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(db_index=True, verbose_name='Data de Início')),
                ('data_fim', models.DateField(db_index=True, verbose_name='Data de Término')),
                ('tipo', models.CharField(choices=[('FERIADO', 'Feriado'), ('RECESSO', 'Recesso Escolar'), ('EMENDA', 'Emenda / Ponto Facultativo'), ('OUTRO', 'Outro Dia Não Letivo')], default='FERIADO', max_length=20, verbose_name='Tipo de Não Letivo')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição / Motivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dias_nao_letivos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dias_nao_letivos', to='presencas.turma', verbose_name='Turma / Sala (Opcional - em branco para todas)')),
            ],
            options={
                'verbose_name': 'Dia Não Letivo / Feriado',
                'verbose_name_plural': 'Dias Não Letivos / Feriados',
                'ordering': ['-data_inicio', 'descricao'],
                'indexes': [models.Index(fields=['data_inicio', 'data_fim'], name='presencas_d_data_in_315c18_idx'), models.Index(fields=['tipo'], name='presencas_d_tipo_72177b_idx')],
            },
        ),
    ]
